package environment

const (
	ENV_MONGO_ADDRESS  string = "HANDYBID_MONGO_ADDRESS"
	ENV_MONGO_DATABASE string = "HANDYBID_MONGO_DATABASE"
	ENV_MONGO_USERNAME string = "HANDYBID_MONGO_USERNAME"
	ENV_MONGO_PASSWORD string = "HANDYBID_MONGO_PASSWORD"
)
